version: '3.3'
services:
  csv-loader:
    image: dbmi/pic-sure-hpds-etl:master_80b2833
    environment:
      - HEAPSIZE=4096
      - GPG_USER=jason_stedman@hms.harvard.edu
      - LOADER_NAME=CSVLoader
    volumes:
      - ./hpds:/opt/local/hpds
    entrypoint: "sh -c -i 'sh create_key.sh && cd /opt/local/hpds && tar -xvzf allConcepts.csv.tgz && cd / && java -Xmx${HEAPSIZE:-2048}m -jar ${LOADER_NAME:-CSVLoader}-jar-with-dependencies.jar '"
